 remote_theme: pages- themes/cayman@v0.2.0:

title: Розробка Web-сайту для компанії вантажних перевезень ФОП Кузьменко А.І.
description: Дипломна робота Кулинича В.Ю

Розробка Web-сайту для компанії вантажних перевезень ФОП Кузьменко А.І.
Кваліфікаційна робота на підтвердження ступеня фахового молодшого
бакалавра ([ВСП «ППФК НТУ «ХПІ»](http://polytechnic.poltava.ua)).
Керівник роботи – Серебреннікова Ірина В’ячеславівна
## Завдання до дипломної роботи
розроблений програмний продукт являє собою Web-
сайт, на якому відображена інформація про компанію, калькулятор для
розраху
розрахунку суми за доставку товару, контакти та форма зворотного зв’язку.
Використати інструментарій: Bootstrap, JavaScript.
